language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
install:
  - sudo apt-get install -y libblas-dev liblapack-dev libatlas-base-dev gfortran
  - pip install --only-binary=numpy,scipy -r requirements.txt
  - pip install -r requirements-test.txt
script: pytest tests/test.py -v
